### PR TITLE
Clarify Requirements

### PR DESCRIPTION
**Pull request by avestuk**
I'm opening this PR to address two issues: 

1. The required number of machines in a cluster is not specifically stated. 
2. The kernel modules page is a little confusing. 

In the current state of this PR, I'm satisfied that the overview page is ready to be reviewed. The system configuration page needs to be checked as it's not clear to me when to run the commands under the //TODO section. If you look at the current docs I think that you're supposed to run them if you have a non-cloud optimized kernel.

### CODE REVIEW

**Comment by actionbuddha** [comment]
I agree the page in its current form is a little confusing. I think we need to be very careful recommending that people install non-default kernels, making clear that it's a hack and only suitable for people who know exactly what they are doing (cloud providers often ship additional modules to support their specialist hardware, or specific optimisations/security fixes).

Ultimately what we want to express is:
- actions for standard default distributions (install kernel-extras package where required for example)
- an expression that what StorageOS *requires* is a set of kernel modules, we'll run with that but there are wider considerations and people should be aware before blindly tinkering

**Comment by avestuk** [comment]
I've made some changes that I think express a sense of "here be dragons" for installing a different kernel version. 

@Arau If you feel that we shouldn't be telling people to use a different OS in the case of Ubuntu 16.04/18.04 AWS and Ubuntu 18.04 GCE then feel free to make changes in this branch

**Comment by Arau** [comment]
Before merging lets squash commits.

**Comment by avestuk** [comment]
Commits squashed. @actionbuddha  are you happy with these changes?

**Pull request merged**
