### PR TITLE
Use templates to set node and cli version

### PR DESCRIPTION
**Pull request by croomes**
Was just trying this out - it works, but might be difficult to merge into the refactor branch.  You can use it to set the latest node & cli version in one place.

### CODE REVIEW

**Comment by oicheryl** [comment]
Thanks - will incorporate into the refactor branch tomorrow.

**Comment by oicheryl** [comment]
Now done in refactor branch.

**Comment by croomes** [comment]
No reason not to merge this into master ahead of refactor PR?

**Comment by croomes** [comment]
Changes merged in refactor PR

**Pull request closed without merging**
