### PR TITLE
Replace live tutorials dashboard with image

### PR DESCRIPTION
**Pull request by oicheryl**

### CODE REVIEW

**Comment by oicheryl** [comment]
It's not a redirect, just a link, so the back button should still work?

**Comment by croomes** [comment]
It's not so obvious that there is a tutorial available without logging into the portal - can it be made more prominent?

**Comment by oicheryl** [comment]
Thanks. I've resized the image so the tutorial is visible - does that suffice?

screen shot 2017-11-08 at 14 28 05

**Comment by croomes** [comment]
yes, that's better - thanks

**Pull request merged**
